@description('The name of the Container Registry')
param registryName string

@description('The Azure region where resources will be deployed')
param location string

@description('The SKU tier for the registry')
param skuTier string = 'Basic'

@description('Enable admin user')
param adminUserEnabled bool = false

@description('Retention policy days')
param retentionPolicyDays int = 7

@description('Soft delete retention days')
param softDeleteRetentionDays int = 7

@description('Enable zone redundancy')
param zoneRedundancy string = 'Disabled'

resource containerRegistry 'Microsoft.ContainerRegistry/registries@2025-05-01-preview' = {
  name: registryName
  location: location
  sku: {
    name: skuTier
    tier: skuTier
  }
  properties: {
    adminUserEnabled: adminUserEnabled
    policies: {
      quarantinePolicy: {
        status: 'disabled'
      }
      trustPolicy: {
        type: 'Notary'
        status: 'disabled'
      }
      retentionPolicy: {
        days: retentionPolicyDays
        status: 'disabled'
      }
      exportPolicy: {
        status: 'enabled'
      }
      azureADAuthenticationAsArmPolicy: {
        status: 'enabled'
      }
      softDeletePolicy: {
        retentionDays: softDeleteRetentionDays
        status: 'disabled'
      }
    }
    encryption: {
      status: 'disabled'
    }
    dataEndpointEnabled: false
    publicNetworkAccess: 'Enabled'
    networkRuleBypassOptions: 'AzureServices'
    networkRuleBypassAllowedForTasks: false
    zoneRedundancy: zoneRedundancy
    anonymousPullEnabled: false
    metadataSearch: 'Disabled'
    roleAssignmentMode: 'LegacyRegistryPermissions'
    autoGeneratedDomainNameLabelScope: 'Unsecure'
  }
}

resource scopeMapAdmin 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: containerRegistry
  name: '_repositories_admin'
  properties: {
    description: 'Admin scope map'
    actions: [
      'repositories/*'
    ]
  }
}

resource scopeMapPull 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: containerRegistry
  name: '_repositories_pull'
  properties: {
    description: 'Pull scope map'
    actions: [
      'repositories/*/read'
    ]
  }
}

resource scopeMapPullMetadataRead 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: containerRegistry
  name: '_repositories_pull_metadata_read'
  properties: {
    description: 'Pull metadata read scope map'
    actions: [
      'repositories/*/read'
      'repositories/*/metadata/read'
    ]
  }
}

resource scopeMapPush 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: containerRegistry
  name: '_repositories_push'
  properties: {
    description: 'Push scope map'
    actions: [
      'repositories/*/write'
      'repositories/*/read'
      'repositories/*/delete'
    ]
  }
}

resource scopeMapPushMetadataWrite 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: containerRegistry
  name: '_repositories_push_metadata_write'
  properties: {
    description: 'Push metadata write scope map'
    actions: [
      'repositories/*/write'
      'repositories/*/read'
      'repositories/*/delete'
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
    ]
  }
}

output id string = containerRegistry.id
output name string = containerRegistry.name
output loginServer string = containerRegistry.properties.loginServer

