"""
Pydantic models for structured incident reports.
"""
from typing import List
from pydantic import BaseModel, Field


class EvidenceItem(BaseModel):
    """Individual piece of evidence supporting the incident analysis."""
    source: str = Field(description="The source of the evidence (e.g., 'Impact Analysis', 'Logs', 'Metrics')")
    finding: str = Field(description="The specific finding or data point")
    severity: str = Field(description="Severity of this specific evidence (High, Medium, Low)")


class IncidentReport(BaseModel):
    """Structured incident report generated by the SRE agent."""
    classification: str = Field(description="The final classification (APP, INFRA, DATABASE, NETWORK, UNKNOWN)")
    summary: str = Field(description="A concise executive summary of the incident (2-3 sentences)")
    root_cause: str = Field(description="The identified or suspected root cause")
    evidence: List[EvidenceItem] = Field(description="List of technical evidence supporting the conclusion")
    recommendations: List[str] = Field(description="Actionable next steps for the engineer")

